FROM ollama/ollama

COPY ./ollama_files /root/.ollama
# C:/Users/bober/PycharmProjects/data-engineering-zoomcamp/07-stock-markets-analytics-zoomcamp/llm-zoomcamp/02-open-source/ollama_files:/root/.ollamaa

CMD ["ollama", "run", "gemma:2b"]