{
 "title": "4.2 LLM quality Metrics",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "LLM as a Judge Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT llm_as_a_judge, COUNT(*) as count\nFROM llm_metrics\nGROUP BY llm_as_a_judge;\n"
    }
   ]
  },
  {
   "title": "LLM negative Sentiment",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT negative_llm_answer, COUNT(*) as count\nFROM llm_metrics\nGROUP BY negative_llm_answer;\n"
    }
   ]
  },
  {
   "title": "Cosine Similarity Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT cosine_similarity_text_llm_answer FROM llm_metrics;"
    }
   ]
  }
 ]
}