apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: metrics-db:5432
    database: chat_monitoring
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      sslmode: disable
      postgresVersion: 1300
