{
 "title": "User Feedback",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Number of User prompts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS human_messages_count\nFROM chat_history\nWHERE message_type = 'user';\n"
    }
   ]
  },
  {
   "title": "Number of feedbacks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(feedback) FROM chat_history LIMIT 50 "
    }
   ]
  },
  {
   "title": "Positive vs negative Feedback",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    feedback, \n    COUNT(*) AS count\nFROM \n    chat_history\nWHERE \n    feedback IN ('thumbs_up', 'thumbs_down')\nGROUP BY \n    feedback;\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    date_trunc('minute', timestamp) AS minute,\n    COUNT(*) AS user_prompts_count\nFROM \n    chat_history\nWHERE \n    message_type = 'user'\nGROUP BY \n    minute\nORDER BY \n    minute;\n"
    }
   ]
  }
 ]
}